name: tutorial1
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: step1
        run: |
          echo "Hello from job1"
          echo "Today's date is $(date)"

  job2:
    runs-on: windows-latest
    steps:
      - name: step2
        run: |
          echo "hello from job 2"
          echo "Today's date is $(date)"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: |
          echo "hello from job 3"
          echo "Today's date is $(date)"

  job4:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: step4
        run: |
          echo "I am job 4"
          echo "Today's date is $(date)"
